# Generated by Django 5.1.7 on 2025-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('summmary', models.TextField()),
                ('school', models.TextField()),
                ('university', models.TextField()),
                ('previous_work', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
